### ISSUE TITLE
Acabar el juego!

### ISSUE THREAD

**Issue by nasivuela** [Adalab/dorcas-s2-evaluacion-intermedia-ElisabetAS#1]
Buen trabajo Eli!

El HTML está espartano pero suficiente para realizar el ejercicio, tu lógica tiene muy buena pinta!!

Te dejo algunas sugerencias con detalle a mejorar:

- Si declaramos las variables arriba de cada scope, mejor que mejor.
- Se ha quedado el contador en el tintero, dale caña, si te surge alguna duda me comentas.
- BONUS extra: ¿Que pasaría si la usuaria pone un valor no númerico en el input? ¿Y si fuera uno númerico mayor que 100 o menor que 1?

A por ello!

**Comment by ElisabetAS** [comment]
He terminado el ejercicio...
Respecto al bonus, he conseguido poner feedback si el valor no es numérico pero no para un número mayor que 100 o menor que 1.

**Comment by nasivuela** [comment]
Ole!!

Algo de info extra, cuando parseamos a integer con `parseInt` un valor NO númerico, el resultado es `NaN`, así que otra opción para ver si la usuaria a introducido un valor no númerico sería checkear en el condicional con la función `isNan( numberBox )` https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/isNaN

Por otro lado para dar feedback cuando el número es mayor que 100 o menor que 1, podriamos pner un primer condicional en el if/else con algo así `if(numberBox > 100 || numberBox < 1) {// feedback aquí}`
